export const HEADER_SIZE = 48;

export const MIN_POST_INDEX_UL_SIZE = 96;
export const MAX_HEADING_SIZE_IN_POST = 56.19;
export const SIDEBAR_PADDING_Y = 32;
export const FOLDED_SIDEBAR_SIZE_UNDER_MD =
  MIN_POST_INDEX_UL_SIZE + MAX_HEADING_SIZE_IN_POST + SIDEBAR_PADDING_Y;
export const POST_INDEX_SECTION_MARGIN_BOTTOM = 16;
